name: Build and Deploy to AKS

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Image tag'
        required: true
env:
  AZURE_CREDENTIALS: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

jobs:
  build:
    name: Build and Push Docker Image to ACR
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ env.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image to ACR
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.AZURE_CLIENT_ID }}
          service_principal_password: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant: ${{ secrets.AZURE_TENANT_ID }}
          registry: "acraksghatest"
          repository: "repos"
          image: "image"
          tag: ${{ inputs.image_tag }}
          dockerfile: ./Dockerfile
          git_access_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          folder: ./
          
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 10
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
